import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx,mdx}",
    "./components/**/*.{ts,tsx}",
    "./content/**/*.mdx",
  ],
  theme: {
    extend: {
      colors: {
        accent: "var(--accent)",
        "accent-hover": "var(--accent-hover)",
        "accent-light": "var(--accent-light)",
        "accent-subtle": "var(--accent-subtle)",
        electron: "var(--color-electron)",
        "sig-on": "var(--color-on)",
        "sig-off": "var(--color-off)",
        "sig-gate": "var(--color-gate)",
        "bg-deep": "var(--bg-deep)",
        "bg-base": "var(--bg-base)",
        "bg-surface": "var(--bg-surface)",
        "bg-surface-2": "var(--bg-surface-2)",
        "bg-subtle": "var(--bg-subtle)",
        "bg-muted": "var(--bg-muted)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        "sidebar-bg": "var(--sidebar-bg)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
      },
      typography: {
        DEFAULT: {
          css: {
            color: "var(--text-secondary)",
            maxWidth: "none",
            fontFamily: "var(--font-sans)",
            fontSize: "1.0625rem",
            lineHeight: "1.8",
            "--tw-prose-bullets": "var(--accent)",
            "--tw-prose-counters": "var(--text-muted)",
            a: {
              color: "var(--accent-light)",
              textDecoration: "none",
              fontWeight: "500",
              borderBottom: "1px solid var(--accent-subtle)",
              transition: "border-color 150ms ease",
              "&:hover": { color: "#fff", borderBottomColor: "var(--accent)" },
            },
            p: { color: "var(--text-secondary)" },
            li: { color: "var(--text-secondary)" },
            "li::marker": { color: "var(--accent)" },
            strong: { color: "var(--text-primary)", fontWeight: "700" },
            em: { color: "var(--text-primary)" },
            h2: {
              color: "var(--text-primary)",
              fontFamily: "var(--font-sans)",
              fontWeight: "800",
              fontSize: "1.6rem",
              letterSpacing: "-0.01em",
              marginTop: "2.75em",
              marginBottom: "0.9em",
              paddingBottom: "0.4em",
              borderBottom: "1px solid var(--border)",
            },
            h3: {
              color: "var(--text-primary)",
              fontFamily: "var(--font-sans)",
              fontWeight: "700",
              fontSize: "1.2rem",
              marginTop: "2em",
            },
            h4: {
              color: "var(--accent-light)",
              fontFamily: "var(--font-sans)",
              fontWeight: "700",
              fontSize: "0.8rem",
              letterSpacing: "0.08em",
              textTransform: "uppercase",
            },
            code: {
              backgroundColor: "var(--bg-surface-2)",
              color: "var(--accent-light)",
              borderRadius: "var(--radius-sm)",
              border: "1px solid var(--border)",
              padding: "0.12em 0.4em",
              fontFamily: "var(--font-mono)",
              fontSize: "0.85em",
              fontWeight: "500",
              "&::before": { content: '""' },
              "&::after": { content: '""' },
            },
            pre: {
              backgroundColor: "var(--bg-surface)",
              border: "1px solid var(--border)",
              borderLeft: "3px solid var(--accent)",
              borderRadius: "var(--radius-md)",
              fontFamily: "var(--font-mono)",
              fontSize: "0.84rem",
              lineHeight: "1.65",
              color: "var(--text-primary)",
              boxShadow: "0 8px 24px rgba(0,0,0,0.35)",
            },
            "pre code": {
              backgroundColor: "transparent",
              border: "none",
              color: "var(--text-primary)",
              padding: "0",
              fontWeight: "400",
              fontSize: "inherit",
            },
            blockquote: {
              borderLeftColor: "var(--accent)",
              borderLeftWidth: "3px",
              backgroundColor: "var(--accent-subtle)",
              borderRadius: "0 var(--radius-md) var(--radius-md) 0",
              padding: "0.6em 1.1em",
              color: "var(--text-primary)",
              fontStyle: "normal",
              fontWeight: "500",
            },
            "blockquote p:first-of-type::before": { content: '""' },
            "blockquote p:last-of-type::after": { content: '""' },
            hr: { borderColor: "var(--border)", marginTop: "3em", marginBottom: "3em" },
            table: { fontSize: "0.9rem" },
            "thead th": {
              color: "var(--text-primary)",
              fontWeight: "700",
              borderBottomColor: "var(--border-strong)",
            },
            "tbody tr": { borderBottomColor: "var(--border)" },
            "tbody td": { color: "var(--text-secondary)" },
          },
        },
      },
    },
  },
  plugins: [typography],
};

export default config;
