import { compileMDX } from "next-mdx-remote/rsc";
import { Callout, Formula, Figure, StatGrid, CodeBlock, Pre } from "@/components/lesson/LessonBlocks";
import {
  // 1.1
  ConductivitySpectrum,
  SiliconLattice,
  DopingDiagram,
  PNJunctionDiagram,
  MosfetCrossSection,
  CmosNandSchematic,
  // 1.2
  LogicGateSymbols,
  NandUniversality,
  KMapDiagram,
  // 1.3
  HalfAdderDiagram,
  FullAdderDiagram,
  RippleCarryDiagram,
  Mux2to1Diagram,
  // 1.4
  SRLatchDiagram,
  DFlipFlopTiming,
  ShiftRegisterDiagram,
  FSMTrafficLight,
  // 1.5
  ClockTimingDiagram,
  VoltageScalingChart,
  // 1.6
  BinaryPlaceValue,
  TwosComplementDiagram,
  FloatFormatsDiagram,
  // 1.7
  MacUnitDiagram,
  SystolicArrayDiagram,
  // curriculum-parity backfill
  BJTStructure,
  CarryLookaheadDiagram,
  DemuxDiagram,
  ComparatorDiagram,
  RippleCounterDiagram,
  // 2.1 CPU
  VonNeumannDiagram,
  FetchExecuteCycle,
  PipelineOverlap,
  ForwardingDiagram,
  SimdLanes,
  // 2.2 GPU
  CpuVsGpuCores,
  SimtWarp,
  GpuHierarchy,
  TensorCoreTile,
  WarpLatencyHiding,
  // 2.3 FPGA
  LutDiagram,
  FpgaFabric,
  DspBlock,
  ZynqSoC,
  // 2.4 Memory
  MemoryPyramid,
  MemoryWall,
  CoalescingDiagram,
  // 2.5 Roofline
  RooflineDiagram,
  ArithmeticIntensitySpectrum,
  // 2.6 Parallelism
  AmdahlCurve,
  ParallelismTypes,
  MicroBatchPipeline,
  // 3.1 ML overview
  MLLandscape,
  DataSplitBar,
  BiasVarianceCurve,
  GradientDescentLandscape,
  // 3.2 Classical ML
  DecisionTreeDiagram,
  EnsembleMethods,
  KMeansClusters,
  ClassicalVsDeep,
  // 3.3 Neural nets
  NeuronMAC,
  ActivationFunctions,
  MLPArchitecture,
  BackpropFlow,
  // 3.4 CNNs
  ConvolutionOp,
  DilatedConvolution,
  PoolingDiagram,
  ResNetSkipBlock,
  ReceptiveField,
  // 3.5 RNNs
  RNNUnroll,
  LSTMCell,
  // 3.6 Training vs inference
  TrainInferenceMemory,
  InferenceModes,
  // 3.7 Evaluation
  ConfusionMatrix,
  ROCCurve,
  ResidualsDiagram,
  // 3.8 Audio / filters
  AudioSampling,
  SpectrogramPipeline,
  ASRPipeline,
  TTSPipeline,
  FilterResponse,
  MelFilterbank,
  // 4.1 Autoencoders
  AutoencoderBottleneck,
  DenoisingAutoencoder,
  // 4.2 VAEs
  VAELatentSpace,
  ReparameterizationTrick,
  // 4.3 GANs
  GANArchitecture,
  ModeCollapse,
  // 4.4 Transformers & Attention
  ScaledDotProductAttention,
  MultiHeadAttention,
  TransformerBlock,
  TransformerFamilies,
  GroupedQueryAttention,
  BPEMerges,
  // 4.5 Pre-training
  PretrainingObjectives,
  ScalingLaws,
  // 4.6 Fine-tuning
  FineTuningHierarchy,
  LoRADecomposition,
  QLoRAMemoryStack,
  // 4.7 Unsloth
  UnslothKernelFusion,
  UnslothSpeedup,
  // 4.8 RAG
  RAGPipeline,
  ChunkingStrategies,
  HybridRetrieval,
  RAGASMetrics,
  // 4.9 Prompting
  PromptingLadder,
  SelfConsistency,
  // 4.3a Diffusion models
  DiffusionForwardReverse,
  UNetDenoiser,
  LatentDiffusionPipeline,
  DiffusionSampling,
  // 4.4a Mixture of experts
  MoELayer,
  ExpertLoadBalancing,
  SparseVsDenseParams,
  // 4.7a Decoding & sampling
  DecodingPipeline,
  TemperatureEffect,
  TopKTopP,
  BeamSearch,
  // 4.9a Multimodal models
  CLIPContrastive,
  ViTPatches,
  VLMArchitecture,
  // Module 5 — Inference Systems Fundamentals
  // 5.1 Types of inference
  InferenceParadigms,
  StreamingTTFT,
  EdgePriority,
  // 5.2 Latency vs throughput
  LatencyThroughputPareto,
  LittlesLaw,
  DynamicBatching,
  // 5.3 Model formats
  ModelFormatJourney,
  TensorRTPipeline,
  FormatDecisionTree,
  // 5.4 Precision
  PrecisionHierarchy,
  FloatBitLayouts,
  QuantizationMapping,
  // 5.5 Data pipelines
  InferencePipeline,
  PaddingBucketing,
  CachingLayers,
  // 5.6 Cost engineering
  HardwareCostBars,
  CascadeRouter,
  BudgetLadder,
  // 5.7 Inference server architecture
  InferenceServerStack,
  TritonServer,
  // Module 6 — Model Optimization & Efficient Inference
  // 6.1 Quantization
  QuantizationLevels,
  QuantGranularity,
  PTQvsQAT,
  SmoothQuantShift,
  // 6.2 Pruning & sparsity
  UnstructuredVsStructured,
  Sparsity24,
  StructuredPruningUnits,
  GradualPruningSchedule,
  // 6.3 Knowledge distillation
  DarkKnowledge,
  DistillationLoss,
  FeatureDistillation,
  // 6.4 Graph optimization
  OperatorFusion,
  FlashAttention,
  CudaGraphs,
  TorchCompileFlow,
  // 6.5 Hardware-aware optimization
  TileAlignment,
  KVCacheQuant,
  SpeculativeDecoding,
  // 6.6 The complete optimization pipeline
  OptimizationPipeline,
  ResNet50Journey,
  // Module 7 — Inference Frameworks & LLM Runtimes
  // 7.1 The LLM serving problem
  VisionVsLLMServing,
  PrefillDecode,
  KVCacheGrowth,
  // 7.2 vLLM
  KVFragmentation,
  PagedAttentionBlocks,
  ContinuousBatching,
  // 7.3 llama.cpp
  GgufQuantLadder,
  GgufBlock,
  SplitOffload,
  // 7.4 Ollama
  OllamaStack,
  // 7.5 TGI
  TgiArchitecture,
  // 7.6 Optimization in practice
  ThroughputKnee,
  GrammarConstrained,
  TensorParallelSplit,
  // 7.7 Framework selection
  FrameworkDecisionTree,
  FrameworkPerfLadder,
  // 7.8 Raspberry Pi
  RPiModelOptions,
  // Module 8 — Hardware Acceleration: FPGA + Edge NPUs
  // 8.1 FPGA architecture
  FpgaBuildingBlocks,
  DspPacking,
  ZynqPsPlFlow,
  // 8.2 HLS to bitstream
  FpgaDesignFlow,
  HlsPragmas,
  DataflowStreaming,
  // 8.3 FPGA quantization
  XnorPopcount,
  FinnPipeline,
  // 8.4 FPGA vs GPU vs CPU
  HardwarePhilosophies,
  LatencyJitter,
  EfficiencyBars,
  // 8.5 NN on PYNQ-Z2
  WhatFitsPynq,
  StreamingConv,
  // 8.6 Vitis AI & DPU
  FinnVsVitis,
  DpuEngine,
  // 8.7 FPGA in practice
  StreamingPipeline,
  EnergyPerInference,
  FpgaToAsic,
  // 8.8 TinyML landscape
  TinyMlSpectrum,
  McuMemoryBudget,
  // 8.9 Arm substrate
  CortexMTiers,
  EthosUStack,
} from "@/components/lesson/diagrams";

const components = {
  Callout,
  Formula,
  Figure,
  StatGrid,
  CodeBlock,
  // Style fenced ```code``` blocks with editor chrome (Modules 7+ are code-heavy).
  pre: Pre,
  // Hand-drawn SVG diagrams (the course "images")
  ConductivitySpectrum,
  SiliconLattice,
  DopingDiagram,
  PNJunctionDiagram,
  MosfetCrossSection,
  CmosNandSchematic,
  LogicGateSymbols,
  NandUniversality,
  KMapDiagram,
  HalfAdderDiagram,
  FullAdderDiagram,
  RippleCarryDiagram,
  Mux2to1Diagram,
  SRLatchDiagram,
  DFlipFlopTiming,
  ShiftRegisterDiagram,
  FSMTrafficLight,
  ClockTimingDiagram,
  VoltageScalingChart,
  BinaryPlaceValue,
  TwosComplementDiagram,
  FloatFormatsDiagram,
  MacUnitDiagram,
  SystolicArrayDiagram,
  BJTStructure,
  CarryLookaheadDiagram,
  DemuxDiagram,
  ComparatorDiagram,
  RippleCounterDiagram,
  // Module 2
  VonNeumannDiagram,
  FetchExecuteCycle,
  PipelineOverlap,
  ForwardingDiagram,
  SimdLanes,
  CpuVsGpuCores,
  SimtWarp,
  GpuHierarchy,
  TensorCoreTile,
  WarpLatencyHiding,
  LutDiagram,
  FpgaFabric,
  DspBlock,
  ZynqSoC,
  MemoryPyramid,
  MemoryWall,
  CoalescingDiagram,
  RooflineDiagram,
  ArithmeticIntensitySpectrum,
  AmdahlCurve,
  ParallelismTypes,
  MicroBatchPipeline,
  // Module 3
  MLLandscape,
  DataSplitBar,
  BiasVarianceCurve,
  GradientDescentLandscape,
  DecisionTreeDiagram,
  EnsembleMethods,
  KMeansClusters,
  ClassicalVsDeep,
  NeuronMAC,
  ActivationFunctions,
  MLPArchitecture,
  BackpropFlow,
  ConvolutionOp,
  DilatedConvolution,
  PoolingDiagram,
  ResNetSkipBlock,
  ReceptiveField,
  RNNUnroll,
  LSTMCell,
  TrainInferenceMemory,
  InferenceModes,
  ConfusionMatrix,
  ROCCurve,
  ResidualsDiagram,
  AudioSampling,
  SpectrogramPipeline,
  ASRPipeline,
  TTSPipeline,
  FilterResponse,
  MelFilterbank,
  AutoencoderBottleneck,
  DenoisingAutoencoder,
  VAELatentSpace,
  ReparameterizationTrick,
  GANArchitecture,
  ModeCollapse,
  ScaledDotProductAttention,
  MultiHeadAttention,
  TransformerBlock,
  TransformerFamilies,
  GroupedQueryAttention,
  BPEMerges,
  PretrainingObjectives,
  ScalingLaws,
  FineTuningHierarchy,
  LoRADecomposition,
  QLoRAMemoryStack,
  UnslothKernelFusion,
  UnslothSpeedup,
  RAGPipeline,
  ChunkingStrategies,
  HybridRetrieval,
  RAGASMetrics,
  PromptingLadder,
  SelfConsistency,
  DiffusionForwardReverse,
  UNetDenoiser,
  LatentDiffusionPipeline,
  DiffusionSampling,
  MoELayer,
  ExpertLoadBalancing,
  SparseVsDenseParams,
  DecodingPipeline,
  TemperatureEffect,
  TopKTopP,
  BeamSearch,
  CLIPContrastive,
  ViTPatches,
  VLMArchitecture,
  // Module 5
  InferenceParadigms,
  StreamingTTFT,
  EdgePriority,
  LatencyThroughputPareto,
  LittlesLaw,
  DynamicBatching,
  ModelFormatJourney,
  TensorRTPipeline,
  FormatDecisionTree,
  PrecisionHierarchy,
  FloatBitLayouts,
  QuantizationMapping,
  InferencePipeline,
  PaddingBucketing,
  CachingLayers,
  HardwareCostBars,
  CascadeRouter,
  BudgetLadder,
  InferenceServerStack,
  TritonServer,
  // Module 6
  QuantizationLevels,
  QuantGranularity,
  PTQvsQAT,
  SmoothQuantShift,
  UnstructuredVsStructured,
  Sparsity24,
  StructuredPruningUnits,
  GradualPruningSchedule,
  DarkKnowledge,
  DistillationLoss,
  FeatureDistillation,
  OperatorFusion,
  FlashAttention,
  CudaGraphs,
  TorchCompileFlow,
  TileAlignment,
  KVCacheQuant,
  SpeculativeDecoding,
  OptimizationPipeline,
  ResNet50Journey,
  // Module 7
  VisionVsLLMServing,
  PrefillDecode,
  KVCacheGrowth,
  KVFragmentation,
  PagedAttentionBlocks,
  ContinuousBatching,
  GgufQuantLadder,
  GgufBlock,
  SplitOffload,
  OllamaStack,
  TgiArchitecture,
  ThroughputKnee,
  GrammarConstrained,
  TensorParallelSplit,
  FrameworkDecisionTree,
  FrameworkPerfLadder,
  RPiModelOptions,
  // Module 8
  FpgaBuildingBlocks,
  DspPacking,
  ZynqPsPlFlow,
  FpgaDesignFlow,
  HlsPragmas,
  DataflowStreaming,
  XnorPopcount,
  FinnPipeline,
  HardwarePhilosophies,
  LatencyJitter,
  EfficiencyBars,
  WhatFitsPynq,
  StreamingConv,
  FinnVsVitis,
  DpuEngine,
  StreamingPipeline,
  EnergyPerInference,
  FpgaToAsic,
  TinyMlSpectrum,
  McuMemoryBudget,
  CortexMTiers,
  EthosUStack,
};

export async function renderMDX(source: string) {
  const { content } = await compileMDX({
    source,
    components,
    options: {
      parseFrontmatter: false,
    },
  });
  return content;
}
